language: python


#before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

cache: pip

install:
   -  pip install requests itsdangerous

script: 
   -  KEY=${TRIGGER_KEY} JOB="yoctobuild-stable" GITHUB_USER="mendersoftware" BRANCH="master" YOCTO_MACHINE="beaglebone" python trigger_yocto_build.py &
   -  KEY=${TRIGGER_KEY} JOB="yoctobuild-stable" GITHUB_USER="mendersoftware" BRANCH="master" YOCTO_MACHINE="vexpress-qemu" python trigger_yocto_build.py &
   -  travis_wait 60 wait


# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"

